apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app.kubernetes.io/name: kcdlondon-scenario01-ghost
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kcdlondon-scenario01-ghost
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
    nodePort: 30080