apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content
  labels:
    app.kubernetes.io/name: kcdlondon-scenario01-ghost
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-class-nas