apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-nas
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  storagePools: "nas-default:aggr1"
allowVolumeExpansion: true