apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-san
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  fsType: "ext4"
mountOptions:
   - discard
reclaimPolicy: Retain
allowVolumeExpansion: true
