apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quotasc-2
  labels:
      scenario: quotas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-nas