kind: Pod
apiVersion: v1
metadata:
  name: busyboxfile
spec:
  volumes:
    - name: nfsstorage
      persistentVolumeClaim:
       claimName: pvc-to-resize-file
  containers:
    - name: busybox
      image: quay.io/trident-mirror/kcduk/busybox:1.31.1
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: nfsstorage
