apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-to-resize-file
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: storage-class-nas